### ISSUE TITLE
NoMethodError (undefined method `merge!' for #<String:0x00000007167978>)

### ISSUE THREAD

**Issue by GeNiuS69** [locomotivecms/engine#772]
After update locomoitve_cms from 2.0.3 to 2.2.2 I can't save existing model's elements.
For update use: http://doc.locomotivecms.com/releases/upgrading-engine

**Comment by ziedbargaoui** [comment]
Hello! I'm using V3 and I want to run a migration, but no clue where and how, I'm using Docker and tried this 

` docker exec engine rake db:migrate VERSION=20180110163335 --trace`

But it didn't have any effect! how did you execute this migration?
